 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/examination_sessions", type: :request do
  # ExaminationSession. As you add validations to ExaminationSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExaminationSession.create! valid_attributes
      get examination_sessions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      examination_session = ExaminationSession.create! valid_attributes
      get examination_session_url(examination_session)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_examination_session_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      examination_session = ExaminationSession.create! valid_attributes
      get edit_examination_session_url(examination_session)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExaminationSession" do
        expect {
          post examination_sessions_url, params: { examination_session: valid_attributes }
        }.to change(ExaminationSession, :count).by(1)
      end

      it "redirects to the created examination_session" do
        post examination_sessions_url, params: { examination_session: valid_attributes }
        expect(response).to redirect_to(examination_session_url(ExaminationSession.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExaminationSession" do
        expect {
          post examination_sessions_url, params: { examination_session: invalid_attributes }
        }.to change(ExaminationSession, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post examination_sessions_url, params: { examination_session: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested examination_session" do
        examination_session = ExaminationSession.create! valid_attributes
        patch examination_session_url(examination_session), params: { examination_session: new_attributes }
        examination_session.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the examination_session" do
        examination_session = ExaminationSession.create! valid_attributes
        patch examination_session_url(examination_session), params: { examination_session: new_attributes }
        examination_session.reload
        expect(response).to redirect_to(examination_session_url(examination_session))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        examination_session = ExaminationSession.create! valid_attributes
        patch examination_session_url(examination_session), params: { examination_session: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested examination_session" do
      examination_session = ExaminationSession.create! valid_attributes
      expect {
        delete examination_session_url(examination_session)
      }.to change(ExaminationSession, :count).by(-1)
    end

    it "redirects to the examination_sessions list" do
      examination_session = ExaminationSession.create! valid_attributes
      delete examination_session_url(examination_session)
      expect(response).to redirect_to(examination_sessions_url)
    end
  end
end
