 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/practitioners", type: :request do
  # Practitioner. As you add validations to Practitioner, be sure to
  # adjust the attributes here as well.

  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Practitioner.create! valid_attributes
      get practitioners_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      practitioner = Practitioner.create! valid_attributes
      get practitioner_url(practitioner)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_practitioner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      practitioner = Practitioner.create! valid_attributes
      get edit_practitioner_url(practitioner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Practitioner" do
        expect {
          post practitioners_url, params: { practitioner: valid_attributes }
        }.to change(Practitioner, :count).by(1)
      end

      it "redirects to the created practitioner" do
        post practitioners_url, params: { practitioner: valid_attributes }
        expect(response).to redirect_to(practitioner_url(Practitioner.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Practitioner" do
        expect {
          post practitioners_url, params: { practitioner: invalid_attributes }
        }.to change(Practitioner, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post practitioners_url, params: { practitioner: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested practitioner" do
        practitioner = Practitioner.create! valid_attributes
        patch practitioner_url(practitioner), params: { practitioner: new_attributes }
        practitioner.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the practitioner" do
        practitioner = Practitioner.create! valid_attributes
        patch practitioner_url(practitioner), params: { practitioner: new_attributes }
        practitioner.reload
        expect(response).to redirect_to(practitioner_url(practitioner))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        practitioner = Practitioner.create! valid_attributes
        patch practitioner_url(practitioner), params: { practitioner: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested practitioner" do
      practitioner = Practitioner.create! valid_attributes
      expect {
        delete practitioner_url(practitioner)
      }.to change(Practitioner, :count).by(-1)
    end

    it "redirects to the practitioners list" do
      practitioner = Practitioner.create! valid_attributes
      delete practitioner_url(practitioner)
      expect(response).to redirect_to(practitioners_url)
    end
  end
end
